config/routes.rb
Rails.application.routes.draw do
  resources :reservations
  resources :menu_categories
  resources :item_categories
  resources :categories
  resources :menus
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'visitors#index'
	devise_for :users, controllers: { registrations: "registrations" }
  resources :items
  resources :users
  resources :accounts
  get 'about' => 'visitors#about'



end

app/models/item_category.rb
class ItemCategory < ApplicationRecord
	belongs_to :item
	belongs_to :category
end

app/controllers/item_categories_controller.rb
class ItemCategoriesController < ApplicationController
  before_action :set_item_category, only: [:show, :edit, :update, :destroy]

  # GET /item_categories
  # GET /item_categories.json
  def index
    @item_categories = ItemCategory.all
  end

  # GET /item_categories/1
  # GET /item_categories/1.json
  def show
  end

  # GET /item_categories/new
  def new
    @item_category = ItemCategory.new
  end

  # GET /item_categories/1/edit
  def edit
  end

  # POST /item_categories
  # POST /item_categories.json
  def create
    @item_category = ItemCategory.new(item_category_params)

    respond_to do |format|
      if @item_category.save
        format.html { redirect_to :back }
        format.json { render :show, status: :created, location: @item_category }
      else
        format.html { render :new }
        format.json { render json: @item_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /item_categories/1
  # PATCH/PUT /item_categories/1.json
  def update
    respond_to do |format|
      if @item_category.update(item_category_params)
        format.html { redirect_to :back }
        format.json { render :show, status: :ok, location: @item_category }
      else
        format.html { render :edit }
        format.json { render json: @item_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /item_categories/1
  # DELETE /item_categories/1.json
  def destroy
    @item_category.destroy
    respond_to do |format|
      format.html { redirect_to item_categories_url, notice: 'Item category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item_category
      @item_category = ItemCategory.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def item_category_params
      params.require(:item_category).permit(:item_id, :category_id, :price, :food, :drink)
    end
end

app/helpers/item_categories_helper.rb
module ItemCategoriesHelper
end

app/views/item_categories/_form.html.erb
<%= simple_form_for(@item_category) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :item_id %>
    <%= f.input :category_id %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/item_categories/edit.html.erb
<h1>Editing Item Category</h1>

<%= render 'form', item_category: @item_category %>

<%= link_to 'Show', @item_category %> |
<%= link_to 'Back', item_categories_path %>

app/views/item_categories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Item Categories</h1>

<table>
  <thead>
    <tr>
      <th>Item</th>
      <th>Category</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @item_categories.each do |item_category| %>
      <tr>
        <td><%= item_category.item_id %></td>
        <td><%= item_category.category_id %></td>
        <td><%= link_to 'Show', item_category %></td>
        <td><%= link_to 'Edit', edit_item_category_path(item_category) %></td>
        <td><%= link_to 'Destroy', item_category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Item Category', new_item_category_path %>

app/views/item_categories/new.html.erb
<h1>New Item Category</h1>

<%= render 'form', item_category: @item_category %>

<%= link_to 'Back', item_categories_path %>

app/views/item_categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Item:</strong>
  <%= @item_category.item_id %>
</p>

<p>
  <strong>Category:</strong>
  <%= @item_category.category_id %>
</p>

<%= link_to 'Edit', edit_item_category_path(@item_category) %> |
<%= link_to 'Back', item_categories_path %>