config/routes.rb
Rails.application.routes.draw do
  resources :reservations
  resources :menu_categories
  resources :item_categories
  resources :categories
  resources :menus
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'visitors#index'
	devise_for :users, controllers: { registrations: "registrations" }
  resources :items
  resources :users
  resources :accounts
  get 'about' => 'visitors#about'



end

app/models/menu_category.rb
class MenuCategory < ApplicationRecord
	belongs_to :menu
	belongs_to :category
end

app/controllers/menu_categories_controller.rb
class MenuCategoriesController < ApplicationController
  before_action :set_menu_category, only: [:show, :edit, :update, :destroy]

  # GET /menu_categories
  # GET /menu_categories.json
  def index
    @menu_categories = MenuCategory.all
  end

  # GET /menu_categories/1
  # GET /menu_categories/1.json
  def show
  end

  # GET /menu_categories/new
  def new
    @menu_category = MenuCategory.new
  end

  # GET /menu_categories/1/edit
  def edit
  end

  # POST /menu_categories
  # POST /menu_categories.json
  def create
    @menu_category = MenuCategory.new(menu_category_params)

    respond_to do |format|
      if @menu_category.save
        format.html { redirect_to :back }
        format.json { render :show, status: :created, location: @menu_category }
      else
        format.html { render :new }
        format.json { render json: @menu_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /menu_categories/1
  # PATCH/PUT /menu_categories/1.json
  def update
    respond_to do |format|
      if @menu_category.update(menu_category_params)
        format.html { redirect_to :back }
        format.json { render :show, status: :ok, location: @menu_category }
      else
        format.html { render :edit }
        format.json { render json: @menu_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /menu_categories/1
  # DELETE /menu_categories/1.json
  def destroy
    @menu_category.destroy
    respond_to do |format|
      format.html { redirect_to menu_categories_url, notice: 'Menu category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_menu_category
      @menu_category = MenuCategory.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def menu_category_params
      params.require(:menu_category).permit(:menu_id, :category_id)
    end
end

app/helpers/menu_categories_helper.rb
module MenuCategoriesHelper
end

app/views/menu_categories/_form.html.erb
<%= simple_form_for(@menu_category) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :menu_id %>
    <%= f.input :category_id %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/menu_categories/edit.html.erb
<h1>Editing Menu Category</h1>

<%= render 'form', menu_category: @menu_category %>

<%= link_to 'Show', @menu_category %> |
<%= link_to 'Back', menu_categories_path %>

app/views/menu_categories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Menu Categories</h1>

<table>
  <thead>
    <tr>
      <th>Menu</th>
      <th>Category</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @menu_categories.each do |menu_category| %>
      <tr>
        <td><%= menu_category.menu_id %></td>
        <td><%= menu_category.category_id %></td>
        <td><%= link_to 'Show', menu_category %></td>
        <td><%= link_to 'Edit', edit_menu_category_path(menu_category) %></td>
        <td><%= link_to 'Destroy', menu_category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Menu Category', new_menu_category_path %>

app/views/menu_categories/new.html.erb
<h1>New Menu Category</h1>

<%= render 'form', menu_category: @menu_category %>

<%= link_to 'Back', menu_categories_path %>

app/views/menu_categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Menu:</strong>
  <%= @menu_category.menu_id %>
</p>

<p>
  <strong>Category:</strong>
  <%= @menu_category.category_id %>
</p>

<%= link_to 'Edit', edit_menu_category_path(@menu_category) %> |
<%= link_to 'Back', menu_categories_path %>